#%RAML 1.0 DataType
type: array
description: Data type describing shipping order records
minItems: 1
items:
  properties:
    shipmentNumber?:
      type: string
    action?:
      type: string
    transportationMode?:
      type: string
    pickupDateBegin?:
      type: string
    pickupDateEnd?:
      type: string
    deliveryDateBegin?:
      type: string
    deliveryDateEnd?:
      type: string
    originName?:
      type: string
    originAddress1?:
      type: string
    originAddress2?:
      type: string
    originCity?:
      type: string
    originState?:
      type: string
    originZip?:
      type: string
    originCountry?:
      type: string
    originPhone?:
      type: string
    originFax?:
      type: string
    originEmail?:
      type: string
    originContactName?:
      type: string
    originEarliestAppointmentTime?:
      type: string
    originLatestAppointmentTime?:
      type: string
    destinationName?:
      type: string
    destinationAddress1?:
      type: string
    destinationAddress2?:
      type: string
    destinationCity?:
      type: string
    destinationState?:
      type: string
    destinationZip?:
      type: string
    destinationCountry?:
      type: string
    destinationPhone?:
      type: string
    destinationFax?:
      type: string
    destinationEmail?:
      type: string
    destinationContactName?:
      type: string
    destinationEarliestAppointmentTime?:
      type: string
    destinationLatestAppointmentTime?:
      type: string
    buyerName?:
      type: string
    customerId?:
      type: string
    customerRemit?:
      type: string
    shipmentProcessingIdentifier?:
      type: string
    specialInstructions?:
      type: string
    partNumber?:
      type: string
    partDescription?:
      type: string
    freightClass?:
      type: string
    monetaryValue?:
      type: string
    shippingQuantity?:
      type: string
    shippingWeightTotal?:
      type: string
    shippingPackaging?:
      type: string
    shippingItemLength?:
      type: string
    shippingItemWidth?:
      type: string
    shippingItemHeight?:
      type: string
    shippingItemTotalCube?:
      type: string
    services?:
      type: string
    referenceType#1?:
      type: string
    referenceValue#1?:
      type: string
    referenceType#2?:
      type: string
    referenceValue#2?:
      type: string
    referenceType#3?:
      type: string
    referenceValue#3?:
      type: string
    referenceType#4?:
      type: string
    referenceValue#4?:
      type: string
    referenceType#5?:
      type: string
    referenceValue#5?:
      type: string
    referenceType#6?:
      type: string
    referenceValue#6?:
      type: string
    referenceType#7?:
      type: string
    referenceValue#7?:
      type: string
    referenceType#8?:
      type: string
    referenceValue#8?:
      type: string
    referenceType#9?:
      type: string
    referenceValue#9?:
      type: string
    referenceType#10?:
      type: string
    referenceValue#10?:
      type: string
    referenceType#11?:
      type: string
    referenceValue#11?:
      type: string
    referenceType#12?:
      type: string
    referenceValue#12?:
      type: string
    referenceType#13?:
      type: string
    referenceValue#13?:
      type: string
    referenceType#14?:
      type: string
    referenceValue#14?:
      type: string
    referenceType#15?:
      type: string
    referenceValue#15?:
      type: string
    referenceType#16?:
      type: string
    referenceValue#16?:
      type: string
